### ISSUE TITLE
[BUG] "Oflline mode still required internet even when the game was installed locally

### ISSUE THREAD

**Issue by xgui4** [CmlLib/CmlLib.Core#113]
**Describe the bug**
When i did try my launcher without a internet connection for testing purpose using this library i always get this error : Unhandled exception. System.Net.Http.HttpRequestException: Resource temporarily unavailable (launchermeta.mojang.com:443) even with the offline launch 

**Logs**
Unhandled exception. System.Net.Http.HttpRequestException: Resource temporarily unavailable (launchermeta.mojang.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CmlLib.Core.VersionLoader.MojangJsonVersionLoaderV2.getManifestStream(CancellationToken cancellationToken)
   at CmlLib.Core.VersionLoader.MojangJsonVersionLoaderV2.getManifest(CancellationToken cancellationToken)
   at CmlLib.Core.VersionLoader.MojangJsonVersionLoaderV2.GetVersionMetadatasAsync(CancellationToken cancellationToken)
   at CmlLib.Core.MinecraftLauncher.GetAllVersionsAsync(CancellationToken cancellationToken)
   at CmlLib.Core.MinecraftLauncher.GetVersionAsync(String versionName, CancellationToken cancellationToken)
   at CmlLib.Core.MinecraftLauncher.ExtractFiles(String versionName, CancellationToken cancellationToken)
   at MinecraftLauncherService.LaunchOfflineSessionAsync() in /home/xgui4/develop/X-Launcher/X_Launcher.Core/Service/MinecraftLauncherService.cs:line 40
   at X_Launcher_CLI.Program.Main(String[] args) in /home/xgui4/develop/X-Launcher/X_Launcher.CLI/Program.cs:line 96
   at X_Launcher_CLI.Program.<Main>(String[] args)

**Environment (please complete the following information):**
 - OS: in both Windows 11 and Linux (Fedora KDE 41) 
 - CmlLib.Core Version: 4.0.3
 - .NET version: .NET 9 (the problem occured in a terminal app)

**Comment by AlphaBs** [comment]
post your code please

**Comment by xgui4** [comment]
are is the code :
```csharp
using CmlLib.Core.Auth;
using CmlLib.Core.ProcessBuilder;
using CmlLib.Core;
using CmlLib.Core.Files;
using X_Launcher_Core.Exception;
using X_Launcher_Core.Model;
using X_Launcher_Core.Utility;

public class MinecraftLauncherService
{
    private readonly Game _game;
    private readonly Launcher _launcher;
    private readonly User _user; 

    public MinecraftLauncherService(Game game, Launcher launcher, User user)
    {
        _game = game;
        _launcher = launcher;
        _user = user;
    }
     
    public async Task LaunchOfflineSessionAsync()
    {
        // Initialize the launcher
        var launcher = new MinecraftLauncher(_launcher.Path);
        // Install and launch the game
        await launcher.InstallAsync(_game.Version);
        
        var process = await launcher.BuildProcessAsync(_game.Version, new MLaunchOption
        {
            Session = MSession.CreateOfflineSession(_user.Name),
            MaximumRamMb = _game.MaxMemory,
            MinimumRamMb = _game.MinMemory,
        });
        process.Start();
    }
}
```

**Comment by NoobNotFound** [comment]
`MSession.CreateOfflineSession()` returns a (fake/offline/no real uid) MSession which will be used to login-in. SO you need to use a local version loader

```csharp
var path = new MinecraftPath();
var parameters = MinecraftLauncherParameters.CreateDefault(path);

// load only the locally installed version 
parameters.VersionLoader = new LocalJsonVersionLoader(path);

// initialize a new launcher with parameters
var launcher = new MinecraftLauncher(parameters);
```
_copied from the wiki_
