### ISSUE TITLE
Forge 1.7.10 

### ISSUE THREAD

**Issue by RehabCZ** [CmlLib/CmlLib.Core#19]
Everytime i try reach process to download Forge 1.7.10-10.13.4.1614 it gives exception
My process var:
**var proccess = launcher.CreateProcess("1.7.10", "10.13.4.1614", launchOptions);**

Given exception:

`System.Net.WebException
  HResult=0x80131509
  Message=The remote server returned an error: (404) Not Found.
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at CmlLib.Core.Downloader.MForge.getInstallerStream(String mcversion, String forgeversion)
   at CmlLib.Core.Downloader.MForge.InstallForge(String mcversion, String forgeversion)
   at CmlLib.Core.CMLauncher.CheckForge(String mcversion, String forgeversion, String java)
   at CmlLib.Core.CMLauncher.CreateProcess(String mcversion, String forgeversion, MLaunchOption option)
   at TestMCLauncher.Form1.buttonPlay_Click(Object sender, EventArgs e) in C:\Users\RehabCZ\Desktop\TestMCLauncher\TestMCLauncher\Form1.cs:line 51
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TestMCLauncher.Program.Main() in C:\Users\RehabCZ\Desktop\TestMCLauncher\TestMCLauncher\Program.cs:line 19
`

**Comment by RehabCZ** [comment]
I did some search in your code and figured out that forge version needs to be in this format 
**"10.13.4.1614-1.7.10"**

But i ran into another issue with triggering process and nothing happens

**Comment by AlphaBs** [comment]
Currently, Forge installer in CmlLib.Core only supports newer forge version (like 1.12.2, 1.13, 1.14~). I will update this later.

Install forge manually and launch forge directly like `launcher.CreateProcess("1.7.10-10.13.4.1614", options)`

**Comment by RehabCZ** [comment]
Nevermind it suddenly works this way
**var proccess = launcher.CreateProcess("1.7.10", "10.13.4.1614-1.7.10", launchOptions);**

Thx man appreciate ur work

**Comment by RehabCZ** [comment]
After a long time, I returned to Cmllib and found that the correct format is:

**var proccess = launcher.CreateProcess("1.7.10", "1.7.10-10.13.4.1614-1.7.10", launchOptions);**

So even 1.7.10 Forge works
