### ISSUE TITLE
Launching with Optifine broken in v3.3.3

### ISSUE THREAD

**Issue by MelonHell** [CmlLib/CmlLib.Core#35]
Launching with Optifine broken in v3.3.3

> [13:16:18] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[13:16:18] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[13:16:18] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: D:\AppData\Roaming\.meloncher\minecraft\libraries\optifine\Optifine\1.12.2_HD_U_G6_pre1\Optifine-1.12.2_HD_U_G6_pre1.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[13:16:18] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186) ~[launchwrapper-of-2.2.jar:2.2]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:155) [launchwrapper-of-2.2.jar:2.2]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:177) ~[launchwrapper-of-2.2.jar:2.2]
        ... 6 more

**Comment by AlphaBs** [comment]
Creating duplicate jar files appears to be the intended behavior of the Optifine team. Even if 1.12.2-Optifine~.jar doesn't exist, it doesn't cause any problems because the library downloads it automatically.
