### ISSUE TITLE
[BUG] System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by bronemishka** [CmlLib/CmlLib.Core#99]
When trying to install latest forge 1.20.1 got this error

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: Name
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at CmlLib.Utils.JarFile.GetManifest()
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.startProcessor(JToken processor, Dictionary`2 mapData)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.StartProcessors(JArray processors, Dictionary`2 mapData)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.MapAndStartProcessors(JObject installProfile, String installerDir)
   at CmlLib.Core.Installer.Forge.Installers.FNewest.Install(String installerDir)
   at CmlLib.Core.Installer.Forge.Installers.ForgeInstaller.Install(ForgeInstallOptions options)
   at CmlLib.Core.Installer.Forge.MForgeNoAds.Install(ForgeVersion forgeVersion, ForgeInstallOptions options, Boolean forceUpdate) in C:\Users\bronemishka\Desktop\git\minecraft-modpack-loader\ModPackLoader\Core\Utils\MForgeNoAds.cs:line 93
   at ModPackLoader.Core.UltimateInstaller.InstallMinecraft() in C:\Users\bronemishka\Desktop\git\minecraft-modpack-loader\ModPackLoader\Core\UltimateInstaller.cs:line 63
   at ModPackLoader.ViewModels.LoaderViewModel.InstallModpack() in C:\Users\bronemishka\Desktop\git\minecraft-modpack-loader\ModPackLoader\ViewModels\LoaderViewModel.cs:line 43
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

**Environment:**
 - OS: win 11
 - CmlLib.Core Version:3.3.10
 - .NET Core 7

**Additional context**
Tried to investigate the problem and found that the reason could be with the IForgeInstallerVersionMapper, so probably somewhere there is the place fix should be done. From my side I just modified MForge to not show the ad.

**Comment by AlphaBs** [comment]
update CmlLib.Core.Installer.Forge 0.0.3
